name: Build and push to aws

on: 
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '6.0'

      - name: Build project
        run: dotnet restore; dotnet publish -o site;

      - name: create zip package
        run:  |
          cd site
          zip -r ../klassupg.zip .
          cd ..


      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: klassupg
          environment_name: Klassupg-env-1
          version_label: ${{ github.run_id }}
          region: eu-north-1
          deployment_package: klassupg.zip
