name: Build-aws

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Build project
        run: |
          cd desktop/projekt
          dotnet restore klassupg.csproj
          dotnet publish klassupg.csproj -o ../../klassupg

      - name: create zip package
        run: |
          cd klassupg
          zip -r ../../klassupg.zip .

      - name: Deploy to aws EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: klassupg
          environment_name: Klassupg-env-1
          version_label: ${{github.run_id}}
          region: eu-north-1
          deployment_package: klassupg.zip
